import type { Metadata } from "next";
import { Poppins, Changa_One } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const changaOne = Changa_One({
  variable: "--font-changa-one",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Seez Utils",
  description:
    "A collection of tools, tiny utilities, and silly little pages—all crafted from my side projects, combining practicality with playfulness.Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${changaOne.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
