import type { Metadata } from "next";
import UtilsClient from "./client";

export const metadata: Metadata = {
  title: "Utilities | Seez Utils",
  description: "A collection of tools, tiny utilities, and silly little pages—all crafted from my side projects, combining practicality with playfulness.Generated by create next app",
  keywords: [
    "utils",
    "tools",
    "utilities",
    "side projects",
    "practical tools",
    "playful utilities",
    "web tools",
  ]
};

export default function UtilsPage() {
  return <UtilsClient />;
}
